### ISSUE TITLE
Post-factum review

### ISSUE THREAD

**Issue by kettanaito** [dandelionadia/to-do-list#1]
## [to-do-list.html](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html)
* [@9](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L9) непотрібний клас `intro` на заголовку
* [@10](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L10) використання класу `block`, який не оголошений в CSS (клас не робить нічого)
* [@12](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L12) використовуй заголовок такого рівня, якій відповідає важливості данних (напевно `<h2>`)
* [@14](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L14) класс `flex-elementoff` не потрібний
* [@15](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L15) елемент `label` має огортати кожен `<input>`, не весь список
* [@15](https://github.com/dandelionadia/to-do-list/blob/master/to-do%20list.html#L15) використай замість `<label>` - `<ul>`, презентуй список завданнь як список в HTML
* Зменш кількість днів і завдань до 2. Менше змін при виправленні.

## [main.css](https://github.com/dandelionadia/to-do-list/blob/master/main.css)
* [@13](https://github.com/dandelionadia/to-do-list/blob/master/main.css#L13) не потрібний класс `flex-elementoff`

**Comment by dandelionadia** [comment]
I have fixed the comments =)
